from fastapi import FastAPI, Depends, HTTPException, status
from sqlalchemy.orm import Session

# Import our custom modules
from app import models, schemas
from app.database import engine, SessionLocal

from typing import List

# 1. Command SQLAlchemy to create the tables in our database
models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# 2. Create the dependency function to manage database sessions
def get_db():
    db = SessionLocal()
    try:
        # yield hands the session to our endpoint, and pauses the function here
        yield db
    finally:
        # When the endpoint is done, the function resumes here and closes the connection
        db.close()

@app.get("/")
async def root():
    return {"message": "Hello World!"}

@app.get("/logs", response_model=List[schemas.AlbumResponse])
def get_logs(db: Session = Depends(get_db)):
    
    # Write a SQLAlchemy query to get all albums. 
    albums = db.query(models.Album).all()
    
    return albums

@app.get("/logs/{id}", response_model=schemas.AlbumResponse)
def get_log_by_id(id: int, db: Session = Depends(get_db)):
    
    # 2. Query the database for the specific ID
    album = db.query(models.Album).filter(models.Album.id == id).first()
    
    # 3. Handle the error if the album doesn't exist
    if not album:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail=f"Album with id {id} was not found"
        )
        
    return album

# We added 'db: Session = Depends(get_db)' to inject our database session!
@app.post("/logs")
async def create_log(log: schemas.AlbumLog, db: Session = Depends(get_db)):
    
    # 3. Create a new SQLAlchemy model instance using the data from Pydantic
    new_album = models.Album(
        title=log.title,
        artist=log.artist,
        rating=log.rating,
        review=log.review
    )
    
    # 4. Stage the new album in our database session
    db.add(new_album)
    
    # 5. Commit the transaction to save it permanently to PostgreSQL
    db.commit()
    
    # Refresh the object so we can see the new ID generated by Postgres
    db.refresh(new_album)
    
    return new_album